<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chao Ma">
<meta name="dcterms.date" content="2026-09-19">

<title>MIT 6.041 Probability: Markov Chains III – ∇ ickma.dev</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-PK5N5KWZBF"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-PK5N5KWZBF', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">∇ ickma.dev</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li class="dropdown-header">Advanced Large Language Model Agents</li>
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/multimodal-agents-perception-to-action.html">
 <span class="dropdown-text">Multimodal Agents: From Perception to Action</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/multimodal-autonomous-ai-agents.html">
 <span class="dropdown-text">Multimodal Autonomous AI Agents</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/coding-agents-vulnerability-detection.html">
 <span class="dropdown-text">Coding Agents and AI for Vulnerability Detection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/open-training-recipes-llm-reasoning.html">
 <span class="dropdown-text">Open Training Recipes: LLM Reasoning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/reasoning-memory-planning-language-agents.html">
 <span class="dropdown-text">Reasoning, Memory, and Planning of Language Agents</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/learning-to-self-improve-and-reason-with-llms.html">
 <span class="dropdown-text">Learning to Self-Improve and Reason with LLMs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/LLM-Agents/inference-time-techniques-for-llm-reasoning.html">
 <span class="dropdown-text">Inference-Time Techniques for LLM Reasoning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">CMU 10-414/714 Deep Learning Systems</li>
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/cmu-dlsys-lecture-6-optimization-initialization.html">
 <span class="dropdown-text">Lecture 6: Optimization and Initialization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/cmu-dlsys-lecture-5-auto-differentiation-implementation.html">
 <span class="dropdown-text">Lecture 5: Auto Differentiation Implementation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/cmu-dlsys-lecture-4-automatic-differentiation.html">
 <span class="dropdown-text">Lecture 4: Automatic Differentiation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/cmu-dlsys-lecture-3-part-2-manual-neural-networks.html">
 <span class="dropdown-text">Lecture 3 Part II: Manual Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/cmu-dlsys-lecture-3-manual-neural-networks.html">
 <span class="dropdown-text">Lecture 3: Manual Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/DLSys/cmu-dlsys-lecture-2-ml-refresher-softmax-regression.html">
 <span class="dropdown-text">Lecture 2: ML Refresher / Softmax Regression</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">ML HW-SW Codesign</li>
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-01-introduction.html">
 <span class="dropdown-text">Efficient AI Lecture 1: Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-03-pruning-and-sparsity-part-1.html">
 <span class="dropdown-text">Efficient AI Lecture 3: Pruning and Sparsity (Part 1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-04-pruning-and-sparsity-part-2.html">
 <span class="dropdown-text">Efficient AI Lecture 4: Pruning and Sparsity (Part II)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-05-quantization-part-1.html">
 <span class="dropdown-text">Efficient AI Lecture 5: Quantization (Part I)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-06-quantization-part-2.html">
 <span class="dropdown-text">Efficient AI Lecture 6: Quantization (Part II)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-07-neural-architecture-search-part-1.html">
 <span class="dropdown-text">Efficient AI Lecture 7: Neural Architecture Search (Part I)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-08-neural-architecture-search-part-2.html">
 <span class="dropdown-text">Efficient AI Lecture 8: Neural Architecture Search (Part II)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-09-knowledge-distillation.html">
 <span class="dropdown-text">Efficient AI Lecture 9: Knowledge Distillation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-10-mcunet-and-tinyml.html">
 <span class="dropdown-text">Efficient AI Lecture 10: MCUNet and TinyML</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-11-tinyengine.html">
 <span class="dropdown-text">Efficient AI Lecture 11: TinyEngine</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-12-transformer-and-llm.html">
 <span class="dropdown-text">Efficient AI Lecture 12: Transformer and LLM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-13-llm-deployment-techniques.html">
 <span class="dropdown-text">Efficient AI Lecture 13: LLM Deployment Techniques</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-14-llm-post-training.html">
 <span class="dropdown-text">Efficient AI Lecture 14: LLM Post-Training</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-15-long-context-llm.html">
 <span class="dropdown-text">Efficient AI Lecture 15: Long-Context LLM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-16-vision-transformer.html">
 <span class="dropdown-text">Efficient AI Lecture 16: Vision Transformer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-17-gans-video-pointcloud.html">
 <span class="dropdown-text">Efficient AI Lecture 17: GANs, Video, and Point Cloud</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-18-diffusion-models.html">
 <span class="dropdown-text">Efficient AI Lecture 18: Diffusion Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-19-distributed-training-part-1.html">
 <span class="dropdown-text">Efficient AI Lecture 19: Distributed Training (Part 1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-20-distributed-training-part-2.html">
 <span class="dropdown-text">Efficient AI Lecture 20: Distributed Training (Part 2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-21-on-device-training-transfer-learning.html">
 <span class="dropdown-text">Efficient AI Lecture 21: On-Device Training and Transfer Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/HW-SW-codesign/efficient-ai-lecture-22-quantum-machine-learning-i.html">
 <span class="dropdown-text">Efficient AI Lecture 22: Quantum Machine Learning I</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">JAX</li>
        <li>
    <a class="dropdown-item" href="../../ML/JAX/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/JAX/jax-numpy.html">
 <span class="dropdown-text">JAX NumPy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/JAX/introducing-flax-nnx.html">
 <span class="dropdown-text">Introducing Flax NNX</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/JAX/jax-ai-stack.html">
 <span class="dropdown-text">JAX AI Stack</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/JAX/scaling-up.html">
 <span class="dropdown-text">Scaling Up</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">NLP</li>
        <li>
    <a class="dropdown-item" href="../../ML/NLP/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/NLP/cmu-advanced-nlp-lecture-21-mixture-of-experts.html">
 <span class="dropdown-text">CMU Advanced NLP Lecture 21: Mixture of Experts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/NLP/cmu-advanced-nlp-lecture-16-reinforcement-learning-for-llms.html">
 <span class="dropdown-text">CMU Advanced NLP Lecture 16: Reinforcement Learning for LLMs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/NLP/cmu-advanced-nlp-lecture-9-decoding-algorithms.html">
 <span class="dropdown-text">CMU Advanced NLP Lecture 9: Decoding Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/NLP/cmu-advanced-nlp-lecture-2-learned-representation.html">
 <span class="dropdown-text">CMU Advanced NLP Lecture 2: Learned Representation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/NLP/cmu-advanced-nlp-lecture-1-introduction-fundamentals.html">
 <span class="dropdown-text">CMU Advanced NLP Lecture 1: Introduction and Fundamentals</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">RL</li>
        <li>
    <a class="dropdown-item" href="../../ML/RL/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-10-classic-games.html">
 <span class="dropdown-text">David Silver Lecture 10: Classic Games</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-9-exploration-and-exploitation.html">
 <span class="dropdown-text">David Silver Lecture 9: Exploration and Exploitation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-8-integrating-learning-and-planning.html">
 <span class="dropdown-text">David Silver Lecture 8: Integrating Learning and Planning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-7-policy-gradient-methods.html">
 <span class="dropdown-text">David Silver Lecture 7: Policy Gradient Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-6-value-function-approximation.html">
 <span class="dropdown-text">David Silver Lecture 6: Value Function Approximation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-5-model-free-control.html">
 <span class="dropdown-text">David Silver Lecture 5: Model-Free Control</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/cmu-advanced-nlp-reinforcement-learning.html">
 <span class="dropdown-text">CMU Advanced NLP: Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-4-model-free-prediction.html">
 <span class="dropdown-text">David Silver Lecture 4: Model-Free Prediction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-3-planning-by-dynamic-programming.html">
 <span class="dropdown-text">David Silver Lecture 3: Planning by Dynamic Programming</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-2-markov-decision-process.html">
 <span class="dropdown-text">David Silver Lecture 2: Markov Decision Process</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/RL/david-silver-lecture-1-introduction-to-reinforcement-learning.html">
 <span class="dropdown-text">David Silver Lecture 1: Introduction to RL</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Papers in Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../ML/papers/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/papers/generative-adversarial-nets.html">
 <span class="dropdown-text">Generative Adversarial Nets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/papers/why-tpu-is-fast-for-dot-product.html">
 <span class="dropdown-text">Why TPU Is Fast for Dot Product</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/papers/transformer-attention-is-all-you-need.html">
 <span class="dropdown-text">Transformer: Attention Is All You Need</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/papers/attention-origin-transformer.html">
 <span class="dropdown-text">Attention: The Origin of Transformer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/papers/batch-normalization.html">
 <span class="dropdown-text">Batch Normalization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/papers/lora.html">
 <span class="dropdown-text">LoRA: Low-Rank Adaptation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../ML/deep-learning-book.html">
 <span class="dropdown-text">Goodfellow Deep Learning Book (Overview)</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../ML/xor-deep-learning.html">
 <span class="dropdown-text">Chapter 6.1: XOR Problem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/likelihood-loss-functions.html">
 <span class="dropdown-text">Chapter 6.2: Loss Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/activation-functions.html">
 <span class="dropdown-text">Chapter 6.3: Activation Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/architecture-design.html">
 <span class="dropdown-text">Chapter 6.4: Architecture Design</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/backpropagation.html">
 <span class="dropdown-text">Chapter 6.5: Back-Propagation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/hessian-prerequisites.html">
 <span class="dropdown-text">Chapter 7 Prerequisites: Hessian Matrix</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/l2-regularization.html">
 <span class="dropdown-text">Chapter 7.1.1: L2 Regularization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/l1-regularization.html">
 <span class="dropdown-text">Chapter 7.1.2: L1 Regularization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/constrained-optimization-regularization.html">
 <span class="dropdown-text">Chapter 7.2: Constrained Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/regularization-underconstrained.html">
 <span class="dropdown-text">Chapter 7.3: Under-Constrained Problems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/dataset-augmentation.html">
 <span class="dropdown-text">Chapter 7.4: Dataset Augmentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/noise-robustness.html">
 <span class="dropdown-text">Chapter 7.5: Noise Robustness</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/semi-supervised-learning.html">
 <span class="dropdown-text">Chapter 7.6: Semi-Supervised Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/multi-task-learning.html">
 <span class="dropdown-text">Chapter 7.7: Multi-Task Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/early-stopping.html">
 <span class="dropdown-text">Chapter 7.8: Early Stopping</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/parameter-tying-sharing.html">
 <span class="dropdown-text">Chapter 7.9: Parameter Tying &amp; Sharing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/representation-sparsity.html">
 <span class="dropdown-text">Chapter 7.10: Sparse Representations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/bagging-ensemble.html">
 <span class="dropdown-text">Chapter 7.11: Bagging &amp; Ensemble Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/dropout.html">
 <span class="dropdown-text">Chapter 7.12: Dropout</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/adversarial-training.html">
 <span class="dropdown-text">Chapter 7.13: Adversarial Training</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/tangent-prop-manifold.html">
 <span class="dropdown-text">Chapter 7.14: Tangent Prop &amp; Manifolds</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/learning-vs-optimization.html">
 <span class="dropdown-text">Chapter 8.1: Learning vs Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/optimization-challenges.html">
 <span class="dropdown-text">Chapter 8.2: Optimization Challenges</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/basic-optimization-algorithms.html">
 <span class="dropdown-text">Chapter 8.3: Basic Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/parameter-initialization.html">
 <span class="dropdown-text">Chapter 8.4: Parameter Initialization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/adaptive-learning-rates.html">
 <span class="dropdown-text">Chapter 8.5: Adaptive Learning Rates</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/second-order-methods.html">
 <span class="dropdown-text">Chapter 8.6: Second-Order Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/optimization-strategies.html">
 <span class="dropdown-text">Chapter 8.7: Optimization Strategies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/convolution-computation.html">
 <span class="dropdown-text">Chapter 9.1: Convolution Computation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-motivation.html">
 <span class="dropdown-text">Chapter 9.2: CNN Motivation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-pooling.html">
 <span class="dropdown-text">Chapter 9.3: Pooling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-infinitely-strong-prior.html">
 <span class="dropdown-text">Chapter 9.4: Infinitely Strong Prior</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/convolutional-functions.html">
 <span class="dropdown-text">Chapter 9.5: Convolutional Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-structured-outputs.html">
 <span class="dropdown-text">Chapter 9.6: Structured Outputs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-data-types.html">
 <span class="dropdown-text">Chapter 9.7: Data Types</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-efficient-convolution.html">
 <span class="dropdown-text">Chapter 9.8: Efficient Convolution</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-unsupervised-learning.html">
 <span class="dropdown-text">Chapter 9.9: Unsupervised Feature Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/cnn-neuroscience.html">
 <span class="dropdown-text">Chapter 9.10: Neuroscientific Basis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-unfold-computation-graph.html">
 <span class="dropdown-text">Chapter 10.1: Unfold Computation Graph</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-recurrent-neural-networks.html">
 <span class="dropdown-text">Chapter 10.2: Recurrent Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-bidirectional.html">
 <span class="dropdown-text">Chapter 10.3: Bidirectional RNN</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-encoder-decoder.html">
 <span class="dropdown-text">Chapter 10.4: Encoder-Decoder Seq2Seq</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-deep.html">
 <span class="dropdown-text">Chapter 10.5: Deep RNN</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-recursive.html">
 <span class="dropdown-text">Chapter 10.6: Recursive Neural Network</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-long-term-dependency.html">
 <span class="dropdown-text">Chapter 10.7: Long-Term Dependencies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-echo-state.html">
 <span class="dropdown-text">Chapter 10.8: Echo State Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-leaky-unit.html">
 <span class="dropdown-text">Chapter 10.9: Leaky Units</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-lstm-gru.html">
 <span class="dropdown-text">Chapter 10.10: LSTM and GRU</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-optimize-long-term.html">
 <span class="dropdown-text">Chapter 10.11: Optimizing Long-Term Dependencies</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/rnn-explicit-memory.html">
 <span class="dropdown-text">Chapter 10.12: Explicit Memory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/practical-methodology.html">
 <span class="dropdown-text">Chapter 11: Practical Methodology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/large-scale-deep-learning.html">
 <span class="dropdown-text">Chapter 12.1: Large-Scale Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/image-preprocessing-normalization.html">
 <span class="dropdown-text">Chapter 12.2: Image Preprocessing and Normalization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/automatic-speech-recognition.html">
 <span class="dropdown-text">Chapter 12.3: Automatic Speech Recognition</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/nlp-applications.html">
 <span class="dropdown-text">Chapter 12.4: NLP Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/other-applications.html">
 <span class="dropdown-text">Chapter 12.5: Other Applications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/linear-factor-models.html">
 <span class="dropdown-text">Chapter 13: Linear Factor Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/autoencoders.html">
 <span class="dropdown-text">Chapter 14: Autoencoders</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/representation-learning.html">
 <span class="dropdown-text">Chapter 15: Representation Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/structured-probabilistic-models.html">
 <span class="dropdown-text">Chapter 16: Structured Probabilistic Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/monte-carlo-methods.html">
 <span class="dropdown-text">Chapter 17: Monte Carlo Methods</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/confronting-partition-function.html">
 <span class="dropdown-text">Chapter 18: Confronting the Partition Function</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/approximate-inference.html">
 <span class="dropdown-text">Chapter 19: Approximate Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/deep-generative-models.html">
 <span class="dropdown-text">Chapter 20: Deep Generative Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-quantum-machine" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Quantum Machine</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-quantum-machine">    
        <li>
    <a class="dropdown-item" href="../../QuantumMachine/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../QuantumMachine/your-first-quantum-experiment.html">
 <span class="dropdown-text">Your First Quantum Experiment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../QuantumMachine/the-math-behind-quantum-entanglement.html">
 <span class="dropdown-text">The Math Behind Quantum Entanglement</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../QuantumMachine/from-zero-to-quantum.html">
 <span class="dropdown-text">From Zero to Quantum</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../QuantumMachine/qiskit-lesson-1-classical-and-quantum-information.html">
 <span class="dropdown-text">Qiskit Lesson 1: Classical and Quantum Information</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../QuantumMachine/qiskit-lesson-2-multiple-systems.html">
 <span class="dropdown-text">Qiskit Lesson 2: Multiple Systems</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../Math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Probability</li>
        <li>
    <a class="dropdown-item" href="../../Math/Probability/index.html">
 <span class="dropdown-text">MIT 6.041 Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/markov-chains-iii.html">
 <span class="dropdown-text">MIT 6.041 Probability: Markov Chains III</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/markov-chains-ii.html">
 <span class="dropdown-text">MIT 6.041 Probability: Markov Chains II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/markov-chains-i.html">
 <span class="dropdown-text">MIT 6.041 Probability: Markov Chains I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/poisson-process-ii.html">
 <span class="dropdown-text">MIT 6.041 Probability: Poisson Process II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/poisson-process-i.html">
 <span class="dropdown-text">MIT 6.041 Probability: Poisson Process I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/bernoulli-process.html">
 <span class="dropdown-text">MIT 6.041 Probability: Bernoulli Process</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/iterated-expectations.html">
 <span class="dropdown-text">MIT 6.041 Probability: Iterated Expectations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/derived-distributions-covariance.html">
 <span class="dropdown-text">MIT 6.041 Probability: Derived Distributions and Covariance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/continuous-bayes-rule-derived-distributions.html">
 <span class="dropdown-text">MIT 6.041 Probability: Continuous Bayes’ Rule and Derived Distributions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/multiple-continuous-random-variables.html">
 <span class="dropdown-text">MIT 6.041 Probability: Multiple Continuous Random Variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/continuous-random-variables.html">
 <span class="dropdown-text">MIT 6.041 Probability: Continuous Random Variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/discrete-random-variables-3.html">
 <span class="dropdown-text">MIT 6.041 Probability: Discrete Random Variables III</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/discrete-random-variables-2.html">
 <span class="dropdown-text">MIT 6.041 Probability: Discrete Random Variables II</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/discrete-random-variables-1.html">
 <span class="dropdown-text">MIT 6.041 Probability: Discrete Random Variables I</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/counting.html">
 <span class="dropdown-text">MIT 6.041 Probability: Counting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/independence.html">
 <span class="dropdown-text">MIT 6.041 Probability: Independence</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/conditioning-bayes-rule.html">
 <span class="dropdown-text">MIT 6.041 Probability: Conditioning and Bayes’ Rule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Probability/probability-models-axioms.html">
 <span class="dropdown-text">MIT 6.041 Probability: Probability Models and Axioms</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Information Theory</li>
        <li>
    <a class="dropdown-item" href="../../Math/InformationTheory/index.html">
 <span class="dropdown-text">Oxford Math Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/InformationTheory/oxford-lecture-1-defining-entropy-information.html">
 <span class="dropdown-text">Oxford Information Theory Lecture 1: Defining Entropy and Information</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/InformationTheory/oxford-lecture-2-basic-properties-information.html">
 <span class="dropdown-text">Oxford Information Theory Lecture 2: Basic Properties of Information</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/InformationTheory/oxford-lecture-3-introducing-codes.html">
 <span class="dropdown-text">Oxford Information Theory Lecture 3: Introducing Codes</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Calculus</li>
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/six-functions-rules-theorems.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Six Functions, Six Rules, and Six Theorems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/differential-equations-of-growth.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Differential Equations of Growth</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/differential-equations-of-motion.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Differential Equations of Motion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/power-series-eulers-great-formula.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Power Series and Euler’s Great Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/linear-approximation-newtons-method.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Linear Approximation and Newton’s Method</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/growth-rates-log-graphs.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Growth Rates and Log Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/derivatives-ln-arcsin.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Derivatives of ln y and arcsin(y)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/limits-continuous-functions.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Limits and Continuous Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/derivative-sin-cos.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Derivative of sin x and cos x</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/product-quotient-rule.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Product Rule and Quotient Rule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/chain-rule.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Chains and the Chain Rule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/big-picture-integral.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Big Picture Integral</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/exponential-function.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: The Exponential Function</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/max-min-second-derivative.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Max, Min, and Second Derivative</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/big-picture-derivatives.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Big Picture on Derivatives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/Calculus/highlights-of-calculus.html">
 <span class="dropdown-text">Gilbert Strang’s Calculus: Highlights</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Reflections &amp; Synthesis</li>
        <li>
    <a class="dropdown-item" href="../../Math/reflections/mit1806-invertibility-connections.html">
 <span class="dropdown-text">Invertibility Connections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/reflections/taylor-euler-fourier.html">
 <span class="dropdown-text">Taylor, Euler, and Fourier</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">MIT 18.06SC Linear Algebra</li>
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture1-geometry.html">
 <span class="dropdown-text">Lecture 1: Geometry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture2-elimination.html">
 <span class="dropdown-text">Lecture 2: Elimination</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture3-multiplication.html">
 <span class="dropdown-text">Lecture 3: Multiplication</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture4-lu-decomposition.html">
 <span class="dropdown-text">Lecture 4: LU Decomposition</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture5-permutations.html">
 <span class="dropdown-text">Lecture 5.1: Permutations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture5-2-transpose.html">
 <span class="dropdown-text">Lecture 5.2: Transpose</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture5-3-spaces.html">
 <span class="dropdown-text">Lecture 5.3: Spaces</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture6-column-null-space.html">
 <span class="dropdown-text">Lecture 6: Column &amp; Null Space</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture7-solving-ax-0.html">
 <span class="dropdown-text">Lecture 7: Solving Ax=0</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture8-solving-ax-b.html">
 <span class="dropdown-text">Lecture 8: Solving Ax=b</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture9-independence-basis-dimension.html">
 <span class="dropdown-text">Lecture 9: Independence, Basis, Dimension</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture10-four-subspaces.html">
 <span class="dropdown-text">Lecture 10: Four Fundamental Subspaces</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture11-matrix-spaces.html">
 <span class="dropdown-text">Lecture 11: Matrix Spaces</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture12-graphs-networks.html">
 <span class="dropdown-text">Lecture 12: Graphs and Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture13-quiz-review.html">
 <span class="dropdown-text">Lecture 13: Quiz 1 Review</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture14-orthogonality.html">
 <span class="dropdown-text">Lecture 14: Orthogonality</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture15-projections.html">
 <span class="dropdown-text">Lecture 15: Projections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture16-least-squares.html">
 <span class="dropdown-text">Lecture 16: Least Squares</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture17-gram-schmidt.html">
 <span class="dropdown-text">Lecture 17: Gram-Schmidt</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture18-determinants.html">
 <span class="dropdown-text">Lecture 18: Determinants</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture19-determinant-formulas.html">
 <span class="dropdown-text">Lecture 19: Determinant Formulas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture20-cramers-rule.html">
 <span class="dropdown-text">Lecture 20: Inverse &amp; Volume</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture21-eigenvalues-eigenvectors.html">
 <span class="dropdown-text">Lecture 21: Eigenvalues &amp; Eigenvectors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture22-diagonalization-powers.html">
 <span class="dropdown-text">Lecture 22: Diagonalization &amp; Powers</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture23-differential-equations.html">
 <span class="dropdown-text">Lecture 23: Differential Equations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture24-markov-fourier.html">
 <span class="dropdown-text">Lecture 24: Markov &amp; Fourier</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture25-symmetric-positive-definite.html">
 <span class="dropdown-text">Lecture 25: Symmetric &amp; Positive Definite</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture26-complex-matrices-fft.html">
 <span class="dropdown-text">Lecture 26: Complex Matrices &amp; FFT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture27-positive-definite-minima.html">
 <span class="dropdown-text">Lecture 27: Positive Definite &amp; Minima</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture28-similar-matrices-jordan.html">
 <span class="dropdown-text">Lecture 28: Similar Matrices &amp; Jordan Form</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture29-svd.html">
 <span class="dropdown-text">Lecture 29: Singular Value Decomposition</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture30-linear-transformations.html">
 <span class="dropdown-text">Lecture 30: Linear Transformations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture31-change-of-basis.html">
 <span class="dropdown-text">Lecture 31: Change of Basis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.06/mit1806-lecture33-left-right-inverse.html">
 <span class="dropdown-text">Lecture 33: Left &amp; Right Inverse</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">MIT 18.065: Linear Algebra Applications</li>
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture1-column-space.html">
 <span class="dropdown-text">Lecture 1: Column Space</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture2-multiplying-factoring.html">
 <span class="dropdown-text">Lecture 2: Multiplying and Factoring Matrices</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture3-orthonormal-columns.html">
 <span class="dropdown-text">Lecture 3: Orthonormal Columns</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture4-eigenvalues-eigenvectors.html">
 <span class="dropdown-text">Lecture 4: Eigenvalues and Eigenvectors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture5-positive-definite.html">
 <span class="dropdown-text">Lecture 5: Positive Definite Matrices</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture6-svd.html">
 <span class="dropdown-text">Lecture 6: Singular Value Decomposition</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture7-eckart-young.html">
 <span class="dropdown-text">Lecture 7: Eckart-Young Theorem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture8-norms.html">
 <span class="dropdown-text">Lecture 8: Norms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture9-least-squares.html">
 <span class="dropdown-text">Lecture 9: Least Squares</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture10-axb-difficulties.html">
 <span class="dropdown-text">Lecture 10: Survey of Ax=b Difficulties</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/lecture-11-minimize-norm-subject-to-constraint.html">
 <span class="dropdown-text">Lecture 11: Minimize Norm subject to Constraint</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture12-eigenvalue-algorithms.html">
 <span class="dropdown-text">Lecture 12: Computing Eigenvalues</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture13-randomized-matrix-multiplication.html">
 <span class="dropdown-text">Lecture 13: Randomized Matrix Multiplication</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture14-low-rank-changes-inverse.html">
 <span class="dropdown-text">Lecture 14: Low Rank Changes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture15-matrix-derivatives.html">
 <span class="dropdown-text">Lecture 15: Matrix Derivatives</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture16-derivative-inverse-singular-values.html">
 <span class="dropdown-text">Lecture 16: Derivative of Inverse and Singular Values</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture17-rapidly-decreasing-singular-values.html">
 <span class="dropdown-text">Lecture 17: Rapidly Decreasing Singular Values</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture18-counting-parameters-svd-lu-qr-saddle-points.html">
 <span class="dropdown-text">Lecture 18: Counting Parameters in SVD, LU, QR, and Saddle Points</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture19-saddle-point-maxmin-principle.html">
 <span class="dropdown-text">Lecture 19: Saddle Point and the Max–Min Principle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture20-probability-definitions-inequalities.html">
 <span class="dropdown-text">Lecture 20: Probability Definitions and Inequalities</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture21-minimizing-function.html">
 <span class="dropdown-text">Lecture 21: Minimizing a Function</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture22-gradient-descent.html">
 <span class="dropdown-text">Lecture 22: Gradient Descent</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture23-accelerating-gradient-descent-momentum.html">
 <span class="dropdown-text">Lecture 23: Accelerating Gradient Descent (Momentum)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture24-linear-programming-two-person-games.html">
 <span class="dropdown-text">Lecture 24: Linear Programming and Two-Person Games</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture25-stochastic-gradient-descent.html">
 <span class="dropdown-text">Lecture 25: Stochastic Gradient Descent</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture26-structure-of-neural-nets.html">
 <span class="dropdown-text">Lecture 26: Structure of Neural Nets for Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture27-backpropagation-partial-gradients.html">
 <span class="dropdown-text">Lecture 27: Back Propagation and Partial Gradients</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture30-completing-rank1-circulants.html">
 <span class="dropdown-text">Lecture 30: Completing a Rank-1 Matrix, Circulants</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture31-fourier-matrix.html">
 <span class="dropdown-text">Lecture 31: Eigenvectors of Circulant Matrices, Fourier Matrix</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture32-convolution-rule.html">
 <span class="dropdown-text">Lecture 32: The Convolution Rule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture34-distance-matrices-procrustes.html">
 <span class="dropdown-text">Lecture 34: Distance Matrices, Procrustes Problem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/MIT18.065/mit18065-lecture35-find-clusters-graph.html">
 <span class="dropdown-text">Lecture 35: Find Clusters in Graph</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Stanford EE 364A: Convex Optimization</li>
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/lectures.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture1-intro.html">
 <span class="dropdown-text">Lecture 1: Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture2-math-foundations.html">
 <span class="dropdown-text">Lecture 2: Convex Sets</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture3-convex-functions.html">
 <span class="dropdown-text">Lecture 3: Convex Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture4-part1-operations-preserving-convexity.html">
 <span class="dropdown-text">Lecture 4.1: Operations Preserving Convexity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture4-part2-conjugate-quasiconvex.html">
 <span class="dropdown-text">Lecture 4.2: Conjugate &amp; Quasiconvex Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture5-part1-log-concave-convex.html">
 <span class="dropdown-text">Lecture 5.1: Log-Concave &amp; Log-Convex</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture5-part2-monotonicity.html">
 <span class="dropdown-text">Lecture 5.2: Monotonicity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture6-optimization-problems.html">
 <span class="dropdown-text">Chapter 4.1: Optimization Problems</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture7-convex-optimization.html">
 <span class="dropdown-text">Chapter 4.2: Convex Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture8-linear-optimization.html">
 <span class="dropdown-text">Chapter 4.3: Linear Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-lecture9-quadratic-optimization.html">
 <span class="dropdown-text">Chapter 4.4: Quadratic Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-chapter4-5-geometric-programming.html">
 <span class="dropdown-text">Chapter 4.5: Geometric Programming</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-chapter4-6-generalized-inequality-constraints.html">
 <span class="dropdown-text">Chapter 4.6: Generalized Inequality Constraints</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-chapter4-7-vector-optimization.html">
 <span class="dropdown-text">Chapter 4.7: Vector Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Math/EE364A/ee364a-chapter5-1-lagrange-dual-function.html">
 <span class="dropdown-text">Chapter 5.1: The Lagrange Dual Function</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-theory-to-repro" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Theory-to-Repro</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-theory-to-repro">    
        <li>
    <a class="dropdown-item" href="../../Theory-to-Repro/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Theory-to-Repro/linear-regression-three-ways.html">
 <span class="dropdown-text">Linear Regression via Three Solvers</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../ML/k_means_clustering.html">
 <span class="dropdown-text">K-Means Clustering</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/logistic_regression.html">
 <span class="dropdown-text">Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../ML/axis.html">
 <span class="dropdown-text">Axis Operations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Algorithm/dp_regex.html">
 <span class="dropdown-text">DP Regex</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-building-startups" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Building Startups</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-building-startups">    
        <li>
    <a class="dropdown-item" href="../../Startups/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Startups/getting-and-evaluating-startup-ideas.html">
 <span class="dropdown-text">Getting and Evaluating Startup Ideas</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/ickma2311/ickma2311.github.io/discussions"> 
<span class="menu-text">Feedback</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#steady-state-does-not-make-neighboring-observations-independent" id="toc-steady-state-does-not-make-neighboring-observations-independent" class="nav-link active" data-scroll-target="#steady-state-does-not-make-neighboring-observations-independent">Steady state does not make neighboring observations independent</a></li>
  <li><a href="#capacity-planning-a-loss-system-has-no-queue" id="toc-capacity-planning-a-loss-system-has-no-queue" class="nav-link" data-scroll-target="#capacity-planning-a-loss-system-has-no-queue">Capacity planning: a loss system has no queue</a>
  <ul class="collapse">
  <li><a href="#why-departures-occur-at-rate-iμ" id="toc-why-departures-occur-at-rate-iμ" class="nav-link" data-scroll-target="#why-departures-occur-at-rate-iμ">Why departures occur at rate iμ</a></li>
  <li><a href="#average-demand-is-not-a-service-level-target" id="toc-average-demand-is-not-a-service-level-target" class="nav-link" data-scroll-target="#average-demand-is-not-a-service-level-target">Average demand is not a service-level target</a></li>
  </ul></li>
  <li><a href="#absorption-probabilities-which-outcome-will-happen" id="toc-absorption-probabilities-which-outcome-will-happen" class="nav-link" data-scroll-target="#absorption-probabilities-which-outcome-will-happen">Absorption probabilities: which outcome will happen?</a></li>
  <li><a href="#expected-time-the-extra-1-is-the-step-you-just-took" id="toc-expected-time-the-extra-1-is-the-step-you-just-took" class="nav-link" data-scroll-target="#expected-time-the-extra-1-is-the-step-you-just-took">Expected time: the extra “1” is the step you just took</a></li>
  <li><a href="#first-arrival-versus-first-return" id="toc-first-arrival-versus-first-return" class="nav-link" data-scroll-target="#first-arrival-versus-first-return">First arrival versus first return</a></li>
  <li><a href="#choosing-the-right-equations" id="toc-choosing-the-right-equations" class="nav-link" data-scroll-target="#choosing-the-right-equations">Choosing the right equations</a></li>
  <li><a href="#sources-and-reproducibility" id="toc-sources-and-reproducibility" class="nav-link" data-scroll-target="#sources-and-reproducibility">Sources and reproducibility</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">MIT 6.041 Probability: Markov Chains III</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chao Ma </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Notes on <strong>MIT 6.041 Probabilistic Systems Analysis and Applied Probability, Lecture 18: Markov Chains III</strong>, taught by John Tsitsiklis.</p>
<p>A telephone exchange receives 30 calls per minute. Each call lasts three minutes on average. That is an offered load of 90 calls—but <strong>90 lines still reject about 8% of incoming calls</strong>. Why isn’t matching average demand enough?</p>
<p>This lecture makes Markov chains answer three operational questions: how much capacity to provide, which terminal outcome a process will reach, and how long it takes to get there. The common technique is to turn the transition graph into equations, with boundary conditions chosen for the question.</p>
<figure class="figure">
<img id="capacity-animation" src="markov-iii-assets/capacity.png" alt="Erlang loss model: 90 lines block 7.957 percent of arrivals, 106 lines block 1.055 percent, and 107 lines block 0.880 percent. The static frame highlights 107 lines; the adjacent curve compares capacities. The animation varies capacity at fixed offered load, not elapsed time." width="1600" height="900" style="width:100%;height:auto" class="figure-img"> <button type="button" id="capacity-toggle" aria-controls="capacity-animation">Play capacity comparison</button>
<figcaption>
Each frame changes the number of lines, holding arrival and service rates fixed. These are exact stationary calculations, not simulated call histories. <a href="markov-iii-assets/capacity.png">Static figure</a> · <a href="markov-iii-assets/capacity-data.csv">Underlying data</a>.
</figcaption>
</figure>
<script>
(() => {
 const img=document.getElementById('capacity-animation');
 const button=document.getElementById('capacity-toggle');
 let playing=!window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 function update(){img.src='markov-iii-assets/capacity.'+(playing?'gif':'png');button.textContent=playing?'Stop animation':'Play capacity comparison';}
 button.addEventListener('click',()=>{playing=!playing;update();});update();
})();
</script>
<iframe style="width:100%;aspect-ratio:16/9;border:0" src="https://www.youtube.com/embed/HIMxdWDLEK8" title="MIT 6.041 Lecture 18: Markov Chains III — John Tsitsiklis" loading="lazy" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
<section id="steady-state-does-not-make-neighboring-observations-independent" class="level2">
<h2 class="anchored" data-anchor-id="steady-state-does-not-make-neighboring-observations-independent">Steady state does not make neighboring observations independent</h2>
<p><a href="../../Math/Probability/markov-chains-ii.html">Lecture 17</a> introduced convergence and balance equations. For the two-state example,</p>
<p><span class="math display">\[
P=\begin{pmatrix}0.5&amp;0.5\\0.2&amp;0.8\end{pmatrix},\qquad
\pi=(2/7,5/7).
\]</span></p>
<p>Let <span class="math inline">\(r_{ij}(n)=P(X_n=j\mid X_0=i)\)</span>. Under the finite-chain convergence conditions discussed previously—one recurrent class, which is aperiodic—<span class="math inline">\(r_{ij}(n)\)</span> approaches <span class="math inline">\(\pi_j\)</span>.</p>
<p>The lecture asks about joint events at different times. Condition on the earlier state and use the Markov property:</p>
<p><span class="math display">\[
P(X_1=1,X_{100}=1\mid X_0=1)
=p_{11}r_{11}(99)\approx\frac12\frac27=\frac17.
\]</span></p>
<p>But for adjacent times,</p>
<p><span class="math display">\[
P(X_{100}=1,X_{101}=2\mid X_0=1)
=r_{11}(100)p_{12}\approx\frac27\frac12=\frac17,
\]</span></p>
<p>not <span class="math inline">\(\pi_1\pi_2=10/49\)</span>. Being late in the process makes the marginal distribution approximately stationary; it does not erase the dependence created by the next transition.</p>
<p><strong>Worked extension:</strong> for this particular matrix, <span class="math inline">\(r_{11}(n)=2/7+(5/7)(0.3)^n\)</span>. The error is tiny after 100 steps. That number of steps is not a general rule: if the cross-state probabilities were 0.001 and 0.002, the corresponding decay factor would be <span class="math inline">\(0.997^n\)</span>, still about 0.74 after 100 steps. Mixing depends on the transition probabilities.</p>
<p>For a contrasting pair of well-separated late times,</p>
<p><span class="math display">\[
P(X_{100}=1,X_{200}=1\mid X_0=1)
=r_{11}(100)r_{11}(100)\approx\pi_1^2=4/49.
\]</span></p>
<p>Here both the time to the first observation and the gap between observations are long relative to this chain’s mixing time. That is why approximate independence is justified in this example, while it fails for adjacent observations.</p>
</section>
<section id="capacity-planning-a-loss-system-has-no-queue" class="level2">
<h2 class="anchored" data-anchor-id="capacity-planning-a-loss-system-has-no-queue">Capacity planning: a loss system has no queue</h2>
<p>Suppose calls arrive according to a Poisson process with rate <span class="math inline">\(\lambda\)</span>, and independent call durations are exponential with rate <span class="math inline">\(\mu\)</span>. There are <span class="math inline">\(B\)</span> lines. An arrival takes a free line immediately or is rejected if all lines are busy.</p>
<p>The state <span class="math inline">\(i\in\{0,\ldots,B\}\)</span> is the number of busy lines. This is a <strong>loss system</strong>, unlike the waiting queue from Lecture 17. Its parameters here are</p>
<p><span class="math display">\[
\lambda=30\text{ calls/min},\qquad
1/\mu=3\text{ min/call},\qquad
a=\lambda/\mu=90.
\]</span></p>
<p>The offered load <span class="math inline">\(a\)</span> is dimensionless, conventionally measured in Erlangs. It is the mean occupancy an unlimited-capacity version would have. It is not the actual mean occupancy after some calls are rejected.</p>
<section id="why-departures-occur-at-rate-iμ" class="level3">
<h3 class="anchored" data-anchor-id="why-departures-occur-at-rate-iμ">Why departures occur at rate iμ</h3>
<p>With <span class="math inline">\(i\)</span> independent exponential calls in progress, the next completion is the minimum of <span class="math inline">\(i\)</span> exponential clocks, so its rate is <span class="math inline">\(i\mu\)</span>. During a small interval <span class="math inline">\(\delta\)</span>,</p>
<p><span class="math display">\[
P(i\to i+1)=\lambda\delta+o(\delta),\qquad
P(i\to i-1)=i\mu\delta+o(\delta).
\]</span></p>
<p>These formulas apply where the neighboring state exists. At <span class="math inline">\(B\)</span>, rejected arrivals do not increase the state; at zero, no departure is possible. Multiple events contribute higher-order terms. The lecture discretizes time into small intervals of length <span class="math inline">\(\delta\)</span> and uses a discrete-time birth–death approximation, rather than developing continuous-time Markov-chain theory. The common factor <span class="math inline">\(\delta\)</span> cancels from the stationary flow-balance equations below.</p>
<p>Across the cut between states <span class="math inline">\(i-1\)</span> and <span class="math inline">\(i\)</span>, stationary flow must balance:</p>
<p><span class="math display">\[
\lambda\pi_{i-1}=i\mu\pi_i.
\]</span></p>
<p>Repeated substitution gives</p>
<p><span class="math display">\[
\pi_i=\pi_0\frac{a^i}{i!},\qquad
\pi_0=\left(\sum_{k=0}^B\frac{a^k}{k!}\right)^{-1}.
\]</span></p>
<p>The distribution resembles a Poisson mass function, truncated at capacity and renormalized. Under the Poisson arrival assumption, arrivals see the stationary occupancy proportions. Thus the fraction of incoming calls rejected is the probability that all lines are busy:</p>
<p><span class="math display">\[
E(B,a)=\pi_B=\frac{a^B/B!}{\sum_{k=0}^B a^k/k!}.
\]</span></p>
</section>
<section id="average-demand-is-not-a-service-level-target" class="level3">
<h3 class="anchored" data-anchor-id="average-demand-is-not-a-service-level-target">Average demand is not a service-level target</h3>
<p>For <span class="math inline">\(a=90\)</span>, direct calculation gives:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Lines B</th>
<th style="text-align: right;">Blocked incoming calls</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">90</td>
<td style="text-align: right;">7.957%</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: right;">2.696%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">106</td>
<td style="text-align: right;">1.055%</td>
</tr>
<tr class="even">
<td style="text-align: right;">107</td>
<td style="text-align: right;">0.880%</td>
</tr>
<tr class="odd">
<td style="text-align: right;">110</td>
<td style="text-align: right;">0.486%</td>
</tr>
</tbody>
</table>
<p>The lecture describes roughly 106 lines for about 1% blocking. <strong>If the requirement is strictly below 1%, the smallest integer is 107.</strong> This is a numerical refinement of the lecture’s approximate example, not a different model.</p>
<p>A stable recursion avoids the large powers and factorials in direct evaluation:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> erlang_b(lines, offered_load):</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    blocking <span class="op">=</span> <span class="fl">1.0</span>  <span class="co"># zero lines: every arrival is rejected</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, lines <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        blocking <span class="op">=</span> offered_load <span class="op">*</span> blocking <span class="op">/</span> (b <span class="op">+</span> offered_load <span class="op">*</span> blocking)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> blocking</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> erlang_b(<span class="dv">106</span>, <span class="dv">90</span>) <span class="op">&gt;</span> <span class="fl">0.01</span> <span class="op">&gt;</span> erlang_b(<span class="dv">107</span>, <span class="dv">90</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The mechanism is variability: occupancy sometimes exceeds its average. Extra lines absorb those fluctuations. <strong>Worked extension:</strong> the mean busy-line count is <span class="math inline">\(a[1-E(B,a)]\)</span>, because accepted arrival rate equals average departure rate. At 90 lines it is about 82.84, even though the offered load is 90.</p>
<p>This model can illustrate admission-controlled servers, but a real system with queues, bursty arrivals, retries, or different service-time structure needs its assumptions checked. This lecture does not establish a universal capacity rule for computing systems.</p>
<div class="callout callout-style-default callout-note callout-titled" title="A related deployment constraint">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A related deployment constraint
</div>
</div>
<div class="callout-body-container callout-body">
<p>Capacity is only one constraint on a deployed model. The first card in <a href="https://dailychat.net/2026-09-14.html?utm_source=ickma_blog&amp;utm_medium=referral&amp;utm_campaign=mit_probability_18&amp;utm_content=capacity_example" id="dailychat-capacity">DailyChat’s “The constraints beyond the model”</a> discusses onboard versus cloud inference, latency, and network variability. It is a separate qualitative systems discussion, not an application of this telephone-loss calculation to robots.</p>
</div>
</div>
</section>
</section>
<section id="absorption-probabilities-which-outcome-will-happen" class="level2">
<h2 class="anchored" data-anchor-id="absorption-probabilities-which-outcome-will-happen">Absorption probabilities: which outcome will happen?</h2>
<p>Now change the question. Instead of long-run occupancy, ask which absorbing state a process reaches. The lecture’s graph has transient states 1, 2, 3 and absorbing states 4, 5:</p>
<ul>
<li>From 1: go to 2 with probability 0.6 or 3 with probability 0.4.</li>
<li>From 2: return to 1 with probability 0.8 or reach 4 with probability 0.2.</li>
<li>From 3: go to 1, 2, or 5 with probabilities 0.5, 0.3, and 0.2.</li>
<li>States 4 and 5 retain the process forever.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="markov-iii-assets/absorption.png" class="img-fluid figure-img"></p>
<figcaption>The lecture’s five-state absorption graph, first-step equations, and calculated probabilities of reaching state 4: 64.3% from state 1, 71.4% from state 2, and 53.6% from state 3.</figcaption>
</figure>
</div>
<p>Let <span class="math inline">\(a_i\)</span> be the probability of eventually reaching 4, starting from <span class="math inline">\(i\)</span>. The boundary conditions are <span class="math inline">\(a_4=1\)</span> and <span class="math inline">\(a_5=0\)</span>. For the remaining states, condition on the first transition:</p>
<p><span class="math display">\[
\begin{aligned}
a_1&amp;=0.6a_2+0.4a_3,\\
a_2&amp;=0.8a_1+0.2,\\
a_3&amp;=0.5a_1+0.3a_2.
\end{aligned}
\]</span></p>
<p>Solving these lecture equations gives</p>
<p><span class="math display">\[
a_1=\frac9{14},\qquad a_2=\frac57,\qquad a_3=\frac{15}{28}.
\]</span></p>
<p>A first-step equation compresses infinitely many possible paths, including repeated returns, into a finite linear system. For example, reaching state 2 does not guarantee reaching 4: the chain may return to 1 and later exit through 5.</p>
<p><strong>Compact extension:</strong> with <span class="math inline">\(Q\)</span> the transient-to-transient transition matrix and <span class="math inline">\(r=(0,0.2,0)^\top\)</span> the direct probabilities of entering 4,</p>
<p><span class="math display">\[
Q=\begin{pmatrix}0&amp;0.6&amp;0.4\\0.8&amp;0&amp;0\\0.5&amp;0.3&amp;0\end{pmatrix},\qquad
(I-Q)a=r.
\]</span></p>
<p>The lecture also uses a useful simplification: when the question only asks which terminal class is reached, collapse each closed recurrent class into a single absorbing state, adding transition probabilities that lead into that class. This preserves the entry outcome; it is not a general license to merge arbitrary states.</p>
<p>In the five-state example above, eventual absorption occurs with probability one, and <span class="math inline">\(I-Q\)</span> is invertible. Do not apply this conclusion blindly if an omitted recurrent class can retain the process indefinitely.</p>
</section>
<section id="expected-time-the-extra-1-is-the-step-you-just-took" class="level2">
<h2 class="anchored" data-anchor-id="expected-time-the-extra-1-is-the-step-you-just-took">Expected time: the extra “1” is the step you just took</h2>
<p>For the expected time to reach a target set <span class="math inline">\(A\)</span>, define</p>
<p><span class="math display">\[
T_A=\inf\{n\ge0:X_n\in A\},\qquad t_i=E[T_A\mid X_0=i].
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
t_i=0\quad(i\in A),\qquad
t_i=1+\sum_jp_{ij}t_j\quad(i\notin A).
\]</span></p>
<p>Compare this with the absorption-probability equation <span class="math inline">\(a_i=\sum_jp_{ij}a_j\)</span>. The averaging mechanism is the same, but elapsed time accumulates a cost of one per transition. Boundary values encode whether we ask about a probability or a waiting time.</p>
<p><strong>Supplementary conditions beyond the lecture’s treatment:</strong> for a finite-state chain, these equations have a unique finite solution on the non-target states when the target is reached almost surely from every state under consideration. If a start state has positive probability of never reaching the target, its unconditional expected hitting time is infinite. Almost-sure hitting alone does not guarantee a finite mean in an infinite-state chain.</p>
<p>The lecture’s next slide changes the graph: state 5 is removed, and state 3 now goes to 1 or 2 with probability 0.5 each. State 4 is the only absorbing outcome. For this revised graph,</p>
<p><span class="math display">\[
\begin{aligned}
t_1&amp;=1+0.6t_2+0.4t_3,\\
t_2&amp;=1+0.8t_1,\\
t_3&amp;=1+0.5t_1+0.5t_2,\qquad t_4=0.
\end{aligned}
\]</span></p>
<p><strong>Calculated solution of the slide’s example:</strong> <span class="math inline">\((t_1,t_2,t_3)=(13.75,12,13.875)\)</span> expected steps. Notice that the graph changed: these are not waiting times for the earlier two-outcome system.</p>
<p>As a separate extension, time to either absorbing outcome in the original graph satisfies <span class="math inline">\((I-Q)t=\mathbf1\)</span>, giving about 9.46 steps from state 1. Applying the lecture’s general merging technique to this example, we merge states 4 and 5 into one “already absorbed” state; probabilities of entering either are added. The resulting first-step waiting-time equations give the same answer. This is different from the conditional time to reach 4 given that 4 is reached.</p>
</section>
<section id="first-arrival-versus-first-return" class="level2">
<h2 class="anchored" data-anchor-id="first-arrival-versus-first-return">First arrival versus first return</h2>
<p>If you start at the target, the first hitting time defined above is zero. A <strong>first return</strong> instead uses</p>
<p><span class="math display">\[
T_s^+=\inf\{n\ge1:X_n=s\}.
\]</span></p>
<p>To calculate a first hitting time, we may replace the target’s outgoing edges with a probability-one self-loop. Transitions after the first arrival cannot change when that arrival occurred. For a first return, however, retain the original first transition from the target and then use those hitting-time values. A return requires at least one transition, even if that transition is a self-loop. First-step analysis gives</p>
<p><span class="math display">\[
t_s^+=1+\sum_jp_{sj}t_j.
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="markov-iii-assets/hitting-return.png" class="img-fluid figure-img"></p>
<figcaption>Two-state transition diagram: 1 to 2 has probability 0.5, 2 to 1 has probability 0.2, and self-loops at 1 and 2 have probabilities 0.5 and 0.8. The stationary distribution is (2/7, 5/7). First hitting state 1 from state 1 takes zero steps; hitting from state 2 takes five expected steps; returning to state 1 takes 1 plus 0.5 times zero plus 0.5 times five, or 3.5 expected steps.</figcaption>
</figure>
</div>
<p>For the two-state chain at the beginning, <span class="math inline">\(t_1=0\)</span> and <span class="math inline">\(t_2=1+0.8t_2\)</span>, so <span class="math inline">\(t_2=5\)</span>. Starting from 1, the first step either returns immediately with probability 0.5 or moves to 2 with probability 0.5:</p>
<p><span class="math display">\[
t_1^+=1+0.5(0)+0.5(5)=3.5.
\]</span></p>
<p><strong>Standard result beyond this lecture, used as a consistency check:</strong> the finite irreducible chain’s mean return time is <span class="math inline">\(1/\pi_1=7/2\)</span>. A state occupied more often in the long run has a shorter mean recurrence interval. Do not confuse this recurrence statement with independence of consecutive states.</p>
</section>
<section id="choosing-the-right-equations" class="level2">
<h2 class="anchored" data-anchor-id="choosing-the-right-equations">Choosing the right equations</h2>
<p>Before calculating, identify the question:</p>
<ul>
<li><strong>Occupancy:</strong> solve stationary flow balance and normalize probabilities.</li>
<li><strong>Eventual destination:</strong> set success/failure boundary values and average after one step.</li>
<li><strong>Time to a target:</strong> set zero time at the target and add one step before averaging.</li>
<li><strong>Time to return:</strong> require a first transition before applying hitting-time values.</li>
</ul>
<p>In the phone example, the useful answer was not simply “average load equals 90.” It was a distribution over occupancy states, a blocking probability, and a capacity tied to an explicit service target. That is what a well-chosen state and the right boundary conditions make possible.</p>
</section>
<section id="sources-and-reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="sources-and-reproducibility">Sources and reproducibility</h2>
<ul>
<li><a href="https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/resources/lecture-18-markov-chains-iii/">MIT OCW lecture page and video</a>, John Tsitsiklis, Fall 2010.</li>
<li><a href="https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/5e411812d2aa2b34818a6df5ff0338b3_MIT6_041F10_L18.pdf">Official Lecture 18 slides</a>.</li>
<li>Source coverage: the complete approximately 51:49 video transcript was read, and the lecture slide pages were visually inspected. This is transcript-and-slide-based coverage, not a claim of watching the entire video. Independently calculated examples and compact matrix notation are marked above.</li>
<li><a href="markov-iii-assets/create_figures.py">Figure code</a>, <a href="markov-iii-assets/capacity-data.csv">capacity data</a>, <a href="markov-iii-assets/validation.json">validation results</a>, and <a href="markov-iii-assets/capacity.mp4">head animation as MP4</a>. Images are programmatically drawn, with exact model values rather than measured traffic data.</li>
<li>Figure workflow used the scientific-visualization skill; see Kassis et al., <a href="https://doi.org/10.48550/arXiv.2609.00065">Scientific Agent Skills: A Library of Procedural Knowledge for Research Agents</a> (2026).</li>
</ul>
<script>
(() => {
 const link=document.getElementById('dailychat-capacity');
 if(!link)return;
 link.addEventListener('click',()=>{
  if(location.hostname==='ickma2311.github.io' && typeof window.gtag==='function'){
   window.gtag('event','dailychat_outbound_click',{article:'markov-chains-iii',link_url:link.href,link_position:'capacity_example',transport_type:'beacon'});
  }
 });
})();
</script>


<!-- -->

<nav class="reader-links" aria-label="Stay connected with Chao">
  <p class="reader-links-eyebrow">Beyond the blog</p>
  <p class="reader-links-title">Stay connected with Chao</p>
  <p class="reader-links-intro">Follow my ideas, say hello, or explore what I’m building.</p>
  <div class="reader-links-items">
    <a class="reader-card reader-card-x" href="https://x.com/ickma2311" target="_blank" rel="noopener noreferrer">
      <span class="reader-card-icon" aria-hidden="true"><svg viewbox="0 0 24 24" fill="currentColor"><path d="M18.9 2H22l-6.8 7.8L23.2 22h-6.3L12 14.6 5.5 22H2.3l8.2-9.4L.8 2h6.5l5.8 7.6L18.9 2Zm-1.1 18h1.7L6.4 3.9H4.6L17.8 20Z"></path></svg></span>
      <span class="reader-card-arrow" aria-hidden="true">↗</span>
      <span class="reader-card-name">X / Twitter</span>
      <span class="reader-card-description">Notes, ideas &amp; things I’m learning.</span>
      <span class="reader-card-action">Follow @ickma2311</span>
    </a>
    <a class="reader-card reader-card-linkedin" href="https://www.linkedin.com/in/chao-ma-929839241/" target="_blank" rel="noopener noreferrer">
      <span class="reader-card-icon" aria-hidden="true"><svg viewbox="0 0 24 24" fill="currentColor"><path d="M20.45 2H3.55C2.69 2 2 2.68 2 3.52v16.96c0 .84.69 1.52 1.55 1.52h16.9c.86 0 1.55-.68 1.55-1.52V3.52c0-.84-.69-1.52-1.55-1.52ZM7.93 18.75H4.98V9.2h2.95v9.55ZM6.45 7.89a1.71 1.71 0 1 1 0-3.42 1.71 1.71 0 0 1 0 3.42Zm12.3 10.86H15.8V14.1c0-1.11-.02-2.54-1.55-2.54-1.55 0-1.79 1.21-1.79 2.46v4.73H9.51V9.2h2.83v1.3h.04c.39-.74 1.36-1.52 2.79-1.52 2.98 0 3.58 1.96 3.58 4.5v5.27Z"></path></svg></span>
      <span class="reader-card-arrow" aria-hidden="true">↗</span>
      <span class="reader-card-name">LinkedIn</span>
      <span class="reader-card-description">Let’s connect over AI, learning &amp; work.</span>
      <span class="reader-card-action">Connect with me</span>
    </a>
    <a class="reader-card reader-card-daily" href="https://dailychat.net/" target="_blank" rel="noopener">
      <span class="reader-card-icon" aria-hidden="true"><svg viewbox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M5 4h14a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-5 3v-3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"></path><path d="m13 7-4 5h4l-2 3 5-5h-4l1-3Z"></path></svg></span>
      <span class="reader-card-arrow" aria-hidden="true">↗</span>
      <span class="reader-card-name">DailyChat</span>
      <span class="reader-card-description">Your quick read on AI &amp; tech.</span>
      <span class="reader-card-action">Explore DailyChat</span>
    </a>
  </div>
</nav>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="light">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "ickma2311/ickma2311.github.io";
    script.dataset.repoId = "R_kgDOOzbaAg";
    script.dataset.category = "Comments";
    script.dataset.categoryId = "DIC_kwDOOzbaAs4CxPFj";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "MIT 6.041 Probability: Markov Chains III"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Chao Ma"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-09-19"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> markov-iii-assets/capacity.png</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">  - markov-iii-assets/**</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>Notes on **MIT 6.041 Probabilistic Systems Analysis and Applied Probability, Lecture 18: Markov Chains III**, taught by John Tsitsiklis.</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>A telephone exchange receives 30 calls per minute. Each call lasts three minutes on average. That is an offered load of 90 calls—but **90 lines still reject about 8% of incoming calls**. Why isn't matching average demand enough?</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>This lecture makes Markov chains answer three operational questions: how much capacity to provide, which terminal outcome a process will reach, and how long it takes to get there. The common technique is to turn the transition graph into equations, with boundary conditions chosen for the question.</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">figure</span><span class="dt">&gt;</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">img</span><span class="ot"> id</span><span class="op">=</span><span class="st">"capacity-animation"</span><span class="ot"> src</span><span class="op">=</span><span class="st">"markov-iii-assets/capacity.png"</span><span class="ot"> alt</span><span class="op">=</span><span class="st">"Erlang loss model: 90 lines block 7.957 percent of arrivals, 106 lines block 1.055 percent, and 107 lines block 0.880 percent. The static frame highlights 107 lines; the adjacent curve compares capacities. The animation varies capacity at fixed offered load, not elapsed time."</span><span class="ot"> width</span><span class="op">=</span><span class="st">"1600"</span><span class="ot"> height</span><span class="op">=</span><span class="st">"900"</span><span class="ot"> style</span><span class="op">=</span><span class="st">"width:100%;height:auto"</span><span class="dt">&gt;</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">button</span><span class="ot"> type</span><span class="op">=</span><span class="st">"button"</span><span class="ot"> id</span><span class="op">=</span><span class="st">"capacity-toggle"</span><span class="ot"> aria-controls</span><span class="op">=</span><span class="st">"capacity-animation"</span><span class="dt">&gt;</span>Play capacity comparison<span class="dt">&lt;/</span><span class="kw">button</span><span class="dt">&gt;</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">figcaption</span><span class="dt">&gt;</span>Each frame changes the number of lines, holding arrival and service rates fixed. These are exact stationary calculations, not simulated call histories. <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"markov-iii-assets/capacity.png"</span><span class="dt">&gt;</span>Static figure<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;</span> · <span class="dt">&lt;</span><span class="kw">a</span><span class="ot"> href</span><span class="op">=</span><span class="st">"markov-iii-assets/capacity-data.csv"</span><span class="dt">&gt;</span>Underlying data<span class="dt">&lt;/</span><span class="kw">a</span><span class="dt">&gt;</span>.<span class="dt">&lt;/</span><span class="kw">figcaption</span><span class="dt">&gt;</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">figure</span><span class="dt">&gt;</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">script</span><span class="dt">&gt;</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>(() <span class="kw">=&gt;</span> {</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a> <span class="kw">const</span> img<span class="op">=</span><span class="bu">document</span><span class="op">.</span><span class="fu">getElementById</span>(<span class="st">'capacity-animation'</span>)<span class="op">;</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a> <span class="kw">const</span> button<span class="op">=</span><span class="bu">document</span><span class="op">.</span><span class="fu">getElementById</span>(<span class="st">'capacity-toggle'</span>)<span class="op">;</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a> <span class="kw">let</span> playing<span class="op">=!</span><span class="bu">window</span><span class="op">.</span><span class="fu">matchMedia</span>(<span class="st">'(prefers-reduced-motion: reduce)'</span>)<span class="op">.</span><span class="at">matches</span><span class="op">;</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a> <span class="kw">function</span> <span class="fu">update</span>(){img<span class="op">.</span><span class="at">src</span><span class="op">=</span><span class="st">'markov-iii-assets/capacity.'</span><span class="op">+</span>(playing<span class="op">?</span><span class="st">'gif'</span><span class="op">:</span><span class="st">'png'</span>)<span class="op">;</span>button<span class="op">.</span><span class="at">textContent</span><span class="op">=</span>playing<span class="op">?</span><span class="st">'Stop animation'</span><span class="op">:</span><span class="st">'Play capacity comparison'</span><span class="op">;</span>}</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a> button<span class="op">.</span><span class="fu">addEventListener</span>(<span class="st">'click'</span><span class="op">,</span>()<span class="kw">=&gt;</span>{playing<span class="op">=!</span>playing<span class="op">;</span><span class="fu">update</span>()<span class="op">;</span>})<span class="op">;</span><span class="fu">update</span>()<span class="op">;</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>})()<span class="op">;</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">script</span><span class="dt">&gt;</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">iframe</span><span class="ot"> style</span><span class="op">=</span><span class="st">"width:100%;aspect-ratio:16/9;border:0"</span><span class="ot"> src</span><span class="op">=</span><span class="st">"https://www.youtube.com/embed/HIMxdWDLEK8"</span><span class="ot"> title</span><span class="op">=</span><span class="st">"MIT 6.041 Lecture 18: Markov Chains III — John Tsitsiklis"</span><span class="ot"> loading</span><span class="op">=</span><span class="st">"lazy"</span><span class="ot"> allow</span><span class="op">=</span><span class="st">"accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"</span><span class="ot"> allowfullscreen</span><span class="dt">&gt;&lt;/</span><span class="kw">iframe</span><span class="dt">&gt;</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Steady state does not make neighboring observations independent</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Lecture 17</span><span class="co">](markov-chains-ii.qmd)</span> introduced convergence and balance equations. For the two-state example,</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>P=\begin{pmatrix}0.5&amp;0.5<span class="sc">\\</span>0.2&amp;0.8\end{pmatrix},\qquad</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>\pi=(2/7,5/7).</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>Let $r_{ij}(n)=P(X_n=j\mid X_0=i)$. Under the finite-chain convergence conditions discussed previously—one recurrent class, which is aperiodic—$r_{ij}(n)$ approaches $\pi_j$.</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>The lecture asks about joint events at different times. Condition on the earlier state and use the Markov property:</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>P(X_1=1,X_{100}=1\mid X_0=1)</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>=p_{11}r_{11}(99)\approx\frac12\frac27=\frac17.</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>But for adjacent times,</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>P(X_{100}=1,X_{101}=2\mid X_0=1)</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>=r_{11}(100)p_{12}\approx\frac27\frac12=\frac17,</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>not $\pi_1\pi_2=10/49$. Being late in the process makes the marginal distribution approximately stationary; it does not erase the dependence created by the next transition.</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>**Worked extension:** for this particular matrix, $r_{11}(n)=2/7+(5/7)(0.3)^n$. The error is tiny after 100 steps. That number of steps is not a general rule: if the cross-state probabilities were 0.001 and 0.002, the corresponding decay factor would be $0.997^n$, still about 0.74 after 100 steps. Mixing depends on the transition probabilities.</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>For a contrasting pair of well-separated late times,</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>P(X_{100}=1,X_{200}=1\mid X_0=1)</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>=r_{11}(100)r_{11}(100)\approx\pi_1^2=4/49.</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>Here both the time to the first observation and the gap between observations are long relative to this chain’s mixing time. That is why approximate independence is justified in this example, while it fails for adjacent observations.</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="fu">## Capacity planning: a loss system has no queue</span></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>Suppose calls arrive according to a Poisson process with rate $\lambda$, and independent call durations are exponential with rate $\mu$. There are $B$ lines. An arrival takes a free line immediately or is rejected if all lines are busy.</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>The state $i\in<span class="sc">\{</span>0,\ldots,B<span class="sc">\}</span>$ is the number of busy lines. This is a **loss system**, unlike the waiting queue from Lecture 17. Its parameters here are</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>\lambda=30\text{ calls/min},\qquad</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>1/\mu=3\text{ min/call},\qquad</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a> a=\lambda/\mu=90.</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>The offered load $a$ is dimensionless, conventionally measured in Erlangs. It is the mean occupancy an unlimited-capacity version would have. It is not the actual mean occupancy after some calls are rejected.</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why departures occur at rate iμ</span></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>With $i$ independent exponential calls in progress, the next completion is the minimum of $i$ exponential clocks, so its rate is $i\mu$. During a small interval $\delta$,</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>P(i\to i+1)=\lambda\delta+o(\delta),\qquad</span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>P(i\to i-1)=i\mu\delta+o(\delta).</span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a>These formulas apply where the neighboring state exists. At $B$, rejected arrivals do not increase the state; at zero, no departure is possible. Multiple events contribute higher-order terms. The lecture discretizes time into small intervals of length $\delta$ and uses a discrete-time birth–death approximation, rather than developing continuous-time Markov-chain theory. The common factor $\delta$ cancels from the stationary flow-balance equations below.</span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>Across the cut between states $i-1$ and $i$, stationary flow must balance:</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>\lambda\pi_{i-1}=i\mu\pi_i.</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a>Repeated substitution gives</span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a>\pi_i=\pi_0\frac{a^i}{i!},\qquad</span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>\pi_0=\left(\sum_{k=0}^B\frac{a^k}{k!}\right)^{-1}.</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a>The distribution resembles a Poisson mass function, truncated at capacity and renormalized. Under the Poisson arrival assumption, arrivals see the stationary occupancy proportions. Thus the fraction of incoming calls rejected is the probability that all lines are busy:</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a>E(B,a)=\pi_B=\frac{a^B/B!}{\sum_{k=0}^B a^k/k!}.</span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a><span class="fu">### Average demand is not a service-level target</span></span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a>For $a=90$, direct calculation gives:</span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lines B <span class="pp">|</span> Blocked incoming calls <span class="pp">|</span></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a><span class="pp">|---:|---:|</span></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 90 <span class="pp">|</span> 7.957% <span class="pp">|</span></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 100 <span class="pp">|</span> 2.696% <span class="pp">|</span></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 106 <span class="pp">|</span> 1.055% <span class="pp">|</span></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 107 <span class="pp">|</span> 0.880% <span class="pp">|</span></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 110 <span class="pp">|</span> 0.486% <span class="pp">|</span></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a>The lecture describes roughly 106 lines for about 1% blocking. **If the requirement is strictly below 1%, the smallest integer is 107.** This is a numerical refinement of the lecture's approximate example, not a different model.</span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a>A stable recursion avoids the large powers and factorials in direct evaluation:</span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a><span class="in">```python</span></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> erlang_b(lines, offered_load):</span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a>    blocking <span class="op">=</span> <span class="fl">1.0</span>  <span class="co"># zero lines: every arrival is rejected</span></span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, lines <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a>        blocking <span class="op">=</span> offered_load <span class="op">*</span> blocking <span class="op">/</span> (b <span class="op">+</span> offered_load <span class="op">*</span> blocking)</span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> blocking</span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> erlang_b(<span class="dv">106</span>, <span class="dv">90</span>) <span class="op">&gt;</span> <span class="fl">0.01</span> <span class="op">&gt;</span> erlang_b(<span class="dv">107</span>, <span class="dv">90</span>)</span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a>The mechanism is variability: occupancy sometimes exceeds its average. Extra lines absorb those fluctuations. **Worked extension:** the mean busy-line count is $a<span class="co">[</span><span class="ot">1-E(B,a)</span><span class="co">]</span>$, because accepted arrival rate equals average departure rate. At 90 lines it is about 82.84, even though the offered load is 90.</span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a>This model can illustrate admission-controlled servers, but a real system with queues, bursty arrivals, retries, or different service-time structure needs its assumptions checked. This lecture does not establish a universal capacity rule for computing systems.</span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="A related deployment constraint"}</span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a>Capacity is only one constraint on a deployed model. The first card in <span class="co">[</span><span class="ot">DailyChat's “The constraints beyond the model”</span><span class="co">](https://dailychat.net/2026-09-14.html?utm_source=ickma_blog&amp;utm_medium=referral&amp;utm_campaign=mit_probability_18&amp;utm_content=capacity_example)</span>{#dailychat-capacity} discusses onboard versus cloud inference, latency, and network variability. It is a separate qualitative systems discussion, not an application of this telephone-loss calculation to robots.</span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a><span class="fu">## Absorption probabilities: which outcome will happen?</span></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a>Now change the question. Instead of long-run occupancy, ask which absorbing state a process reaches. The lecture's graph has transient states 1, 2, 3 and absorbing states 4, 5:</span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>From 1: go to 2 with probability 0.6 or 3 with probability 0.4.</span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>From 2: return to 1 with probability 0.8 or reach 4 with probability 0.2.</span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>From 3: go to 1, 2, or 5 with probabilities 0.5, 0.3, and 0.2.</span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>States 4 and 5 retain the process forever.</span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a><span class="al">![The lecture's five-state absorption graph, first-step equations, and calculated probabilities of reaching state 4: 64.3% from state 1, 71.4% from state 2, and 53.6% from state 3.](markov-iii-assets/absorption.png)</span></span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a>Let $a_i$ be the probability of eventually reaching 4, starting from $i$. The boundary conditions are $a_4=1$ and $a_5=0$. For the remaining states, condition on the first transition:</span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a>a_1&amp;=0.6a_2+0.4a_3,<span class="sc">\\</span></span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a>a_2&amp;=0.8a_1+0.2,<span class="sc">\\</span></span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a>a_3&amp;=0.5a_1+0.3a_2.</span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a>Solving these lecture equations gives</span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a>a_1=\frac9{14},\qquad a_2=\frac57,\qquad a_3=\frac{15}{28}.</span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a>A first-step equation compresses infinitely many possible paths, including repeated returns, into a finite linear system. For example, reaching state 2 does not guarantee reaching 4: the chain may return to 1 and later exit through 5.</span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a>**Compact extension:** with $Q$ the transient-to-transient transition matrix and $r=(0,0.2,0)^\top$ the direct probabilities of entering 4,</span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a>Q=\begin{pmatrix}0&amp;0.6&amp;0.4<span class="sc">\\</span>0.8&amp;0&amp;0<span class="sc">\\</span>0.5&amp;0.3&amp;0\end{pmatrix},\qquad</span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a>(I-Q)a=r.</span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a>The lecture also uses a useful simplification: when the question only asks which terminal class is reached, collapse each closed recurrent class into a single absorbing state, adding transition probabilities that lead into that class. This preserves the entry outcome; it is not a general license to merge arbitrary states.</span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a>In the five-state example above, eventual absorption occurs with probability one, and $I-Q$ is invertible. Do not apply this conclusion blindly if an omitted recurrent class can retain the process indefinitely.</span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a><span class="fu">## Expected time: the extra “1” is the step you just took</span></span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a>For the expected time to reach a target set $A$, define</span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a>T_A=\inf<span class="sc">\{</span>n\ge0:X_n\in A<span class="sc">\}</span>,\qquad t_i=E<span class="co">[</span><span class="ot">T_A\mid X_0=i</span><span class="co">]</span>.</span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-197"><a href="#cb2-197" aria-hidden="true" tabindex="-1"></a>Then</span>
<span id="cb2-198"><a href="#cb2-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-199"><a href="#cb2-199" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-200"><a href="#cb2-200" aria-hidden="true" tabindex="-1"></a>t_i=0\quad(i\in A),\qquad</span>
<span id="cb2-201"><a href="#cb2-201" aria-hidden="true" tabindex="-1"></a>t_i=1+\sum_jp_{ij}t_j\quad(i\notin A).</span>
<span id="cb2-202"><a href="#cb2-202" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-203"><a href="#cb2-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-204"><a href="#cb2-204" aria-hidden="true" tabindex="-1"></a>Compare this with the absorption-probability equation $a_i=\sum_jp_{ij}a_j$. The averaging mechanism is the same, but elapsed time accumulates a cost of one per transition. Boundary values encode whether we ask about a probability or a waiting time.</span>
<span id="cb2-205"><a href="#cb2-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-206"><a href="#cb2-206" aria-hidden="true" tabindex="-1"></a>**Supplementary conditions beyond the lecture’s treatment:** for a finite-state chain, these equations have a unique finite solution on the non-target states when the target is reached almost surely from every state under consideration. If a start state has positive probability of never reaching the target, its unconditional expected hitting time is infinite. Almost-sure hitting alone does not guarantee a finite mean in an infinite-state chain.</span>
<span id="cb2-207"><a href="#cb2-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-208"><a href="#cb2-208" aria-hidden="true" tabindex="-1"></a>The lecture's next slide changes the graph: state 5 is removed, and state 3 now goes to 1 or 2 with probability 0.5 each. State 4 is the only absorbing outcome. For this revised graph,</span>
<span id="cb2-209"><a href="#cb2-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-210"><a href="#cb2-210" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-211"><a href="#cb2-211" aria-hidden="true" tabindex="-1"></a>\begin{aligned}</span>
<span id="cb2-212"><a href="#cb2-212" aria-hidden="true" tabindex="-1"></a>t_1&amp;=1+0.6t_2+0.4t_3,<span class="sc">\\</span></span>
<span id="cb2-213"><a href="#cb2-213" aria-hidden="true" tabindex="-1"></a>t_2&amp;=1+0.8t_1,<span class="sc">\\</span></span>
<span id="cb2-214"><a href="#cb2-214" aria-hidden="true" tabindex="-1"></a>t_3&amp;=1+0.5t_1+0.5t_2,\qquad t_4=0.</span>
<span id="cb2-215"><a href="#cb2-215" aria-hidden="true" tabindex="-1"></a>\end{aligned}</span>
<span id="cb2-216"><a href="#cb2-216" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-217"><a href="#cb2-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-218"><a href="#cb2-218" aria-hidden="true" tabindex="-1"></a>**Calculated solution of the slide's example:** $(t_1,t_2,t_3)=(13.75,12,13.875)$ expected steps. Notice that the graph changed: these are not waiting times for the earlier two-outcome system.</span>
<span id="cb2-219"><a href="#cb2-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-220"><a href="#cb2-220" aria-hidden="true" tabindex="-1"></a>As a separate extension, time to either absorbing outcome in the original graph satisfies $(I-Q)t=\mathbf1$, giving about 9.46 steps from state 1. Applying the lecture’s general merging technique to this example, we merge states 4 and 5 into one “already absorbed” state; probabilities of entering either are added. The resulting first-step waiting-time equations give the same answer. This is different from the conditional time to reach 4 given that 4 is reached.</span>
<span id="cb2-221"><a href="#cb2-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-222"><a href="#cb2-222" aria-hidden="true" tabindex="-1"></a><span class="fu">## First arrival versus first return</span></span>
<span id="cb2-223"><a href="#cb2-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-224"><a href="#cb2-224" aria-hidden="true" tabindex="-1"></a>If you start at the target, the first hitting time defined above is zero. A **first return** instead uses</span>
<span id="cb2-225"><a href="#cb2-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-226"><a href="#cb2-226" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-227"><a href="#cb2-227" aria-hidden="true" tabindex="-1"></a>T_s^+=\inf<span class="sc">\{</span>n\ge1:X_n=s<span class="sc">\}</span>.</span>
<span id="cb2-228"><a href="#cb2-228" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-229"><a href="#cb2-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-230"><a href="#cb2-230" aria-hidden="true" tabindex="-1"></a>To calculate a first hitting time, we may replace the target’s outgoing edges with a probability-one self-loop. Transitions after the first arrival cannot change when that arrival occurred. For a first return, however, retain the original first transition from the target and then use those hitting-time values. A return requires at least one transition, even if that transition is a self-loop. First-step analysis gives</span>
<span id="cb2-231"><a href="#cb2-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-232"><a href="#cb2-232" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-233"><a href="#cb2-233" aria-hidden="true" tabindex="-1"></a>t_s^+=1+\sum_jp_{sj}t_j.</span>
<span id="cb2-234"><a href="#cb2-234" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-235"><a href="#cb2-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-236"><a href="#cb2-236" aria-hidden="true" tabindex="-1"></a><span class="al">![Two-state transition diagram: 1 to 2 has probability 0.5, 2 to 1 has probability 0.2, and self-loops at 1 and 2 have probabilities 0.5 and 0.8. The stationary distribution is (2/7, 5/7). First hitting state 1 from state 1 takes zero steps; hitting from state 2 takes five expected steps; returning to state 1 takes 1 plus 0.5 times zero plus 0.5 times five, or 3.5 expected steps.](markov-iii-assets/hitting-return.png)</span></span>
<span id="cb2-237"><a href="#cb2-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-238"><a href="#cb2-238" aria-hidden="true" tabindex="-1"></a>For the two-state chain at the beginning, $t_1=0$ and $t_2=1+0.8t_2$, so $t_2=5$. Starting from 1, the first step either returns immediately with probability 0.5 or moves to 2 with probability 0.5:</span>
<span id="cb2-239"><a href="#cb2-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-240"><a href="#cb2-240" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-241"><a href="#cb2-241" aria-hidden="true" tabindex="-1"></a>t_1^+=1+0.5(0)+0.5(5)=3.5.</span>
<span id="cb2-242"><a href="#cb2-242" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb2-243"><a href="#cb2-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-244"><a href="#cb2-244" aria-hidden="true" tabindex="-1"></a>**Standard result beyond this lecture, used as a consistency check:** the finite irreducible chain's mean return time is $1/\pi_1=7/2$. A state occupied more often in the long run has a shorter mean recurrence interval. Do not confuse this recurrence statement with independence of consecutive states.</span>
<span id="cb2-245"><a href="#cb2-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-246"><a href="#cb2-246" aria-hidden="true" tabindex="-1"></a><span class="fu">## Choosing the right equations</span></span>
<span id="cb2-247"><a href="#cb2-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-248"><a href="#cb2-248" aria-hidden="true" tabindex="-1"></a>Before calculating, identify the question:</span>
<span id="cb2-249"><a href="#cb2-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-250"><a href="#cb2-250" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Occupancy:** solve stationary flow balance and normalize probabilities.</span>
<span id="cb2-251"><a href="#cb2-251" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Eventual destination:** set success/failure boundary values and average after one step.</span>
<span id="cb2-252"><a href="#cb2-252" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Time to a target:** set zero time at the target and add one step before averaging.</span>
<span id="cb2-253"><a href="#cb2-253" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Time to return:** require a first transition before applying hitting-time values.</span>
<span id="cb2-254"><a href="#cb2-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-255"><a href="#cb2-255" aria-hidden="true" tabindex="-1"></a>In the phone example, the useful answer was not simply “average load equals 90.” It was a distribution over occupancy states, a blocking probability, and a capacity tied to an explicit service target. That is what a well-chosen state and the right boundary conditions make possible.</span>
<span id="cb2-256"><a href="#cb2-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-257"><a href="#cb2-257" aria-hidden="true" tabindex="-1"></a><span class="fu">## Sources and reproducibility</span></span>
<span id="cb2-258"><a href="#cb2-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-259"><a href="#cb2-259" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">MIT OCW lecture page and video</span><span class="co">](https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/resources/lecture-18-markov-chains-iii/)</span>, John Tsitsiklis, Fall 2010.</span>
<span id="cb2-260"><a href="#cb2-260" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Official Lecture 18 slides</span><span class="co">](https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/5e411812d2aa2b34818a6df5ff0338b3_MIT6_041F10_L18.pdf)</span>.</span>
<span id="cb2-261"><a href="#cb2-261" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Source coverage: the complete approximately 51:49 video transcript was read, and the lecture slide pages were visually inspected. This is transcript-and-slide-based coverage, not a claim of watching the entire video. Independently calculated examples and compact matrix notation are marked above.</span>
<span id="cb2-262"><a href="#cb2-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Figure code</span><span class="co">](markov-iii-assets/create_figures.py)</span>, <span class="co">[</span><span class="ot">capacity data</span><span class="co">](markov-iii-assets/capacity-data.csv)</span>, <span class="co">[</span><span class="ot">validation results</span><span class="co">](markov-iii-assets/validation.json)</span>, and <span class="co">[</span><span class="ot">head animation as MP4</span><span class="co">](markov-iii-assets/capacity.mp4)</span>. Images are programmatically drawn, with exact model values rather than measured traffic data.</span>
<span id="cb2-263"><a href="#cb2-263" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Figure workflow used the scientific-visualization skill; see Kassis et al., <span class="co">[</span><span class="ot">Scientific Agent Skills: A Library of Procedural Knowledge for Research Agents</span><span class="co">](https://doi.org/10.48550/arXiv.2609.00065)</span> (2026).</span>
<span id="cb2-264"><a href="#cb2-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-265"><a href="#cb2-265" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;</span><span class="kw">script</span><span class="dt">&gt;</span></span>
<span id="cb2-266"><a href="#cb2-266" aria-hidden="true" tabindex="-1"></a>(() <span class="kw">=&gt;</span> {</span>
<span id="cb2-267"><a href="#cb2-267" aria-hidden="true" tabindex="-1"></a> <span class="kw">const</span> link<span class="op">=</span><span class="bu">document</span><span class="op">.</span><span class="fu">getElementById</span>(<span class="st">'dailychat-capacity'</span>)<span class="op">;</span></span>
<span id="cb2-268"><a href="#cb2-268" aria-hidden="true" tabindex="-1"></a> <span class="cf">if</span>(<span class="op">!</span>link)<span class="cf">return</span><span class="op">;</span></span>
<span id="cb2-269"><a href="#cb2-269" aria-hidden="true" tabindex="-1"></a> link<span class="op">.</span><span class="fu">addEventListener</span>(<span class="st">'click'</span><span class="op">,</span>()<span class="kw">=&gt;</span>{</span>
<span id="cb2-270"><a href="#cb2-270" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(location<span class="op">.</span><span class="at">hostname</span><span class="op">===</span><span class="st">'ickma2311.github.io'</span> <span class="op">&amp;&amp;</span> <span class="kw">typeof</span> <span class="bu">window</span><span class="op">.</span><span class="at">gtag</span><span class="op">===</span><span class="st">'function'</span>){</span>
<span id="cb2-271"><a href="#cb2-271" aria-hidden="true" tabindex="-1"></a>   <span class="bu">window</span><span class="op">.</span><span class="fu">gtag</span>(<span class="st">'event'</span><span class="op">,</span><span class="st">'dailychat_outbound_click'</span><span class="op">,</span>{<span class="dt">article</span><span class="op">:</span><span class="st">'markov-chains-iii'</span><span class="op">,</span><span class="dt">link_url</span><span class="op">:</span>link<span class="op">.</span><span class="at">href</span><span class="op">,</span><span class="dt">link_position</span><span class="op">:</span><span class="st">'capacity_example'</span><span class="op">,</span><span class="dt">transport_type</span><span class="op">:</span><span class="st">'beacon'</span>})<span class="op">;</span></span>
<span id="cb2-272"><a href="#cb2-272" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb2-273"><a href="#cb2-273" aria-hidden="true" tabindex="-1"></a> })<span class="op">;</span></span>
<span id="cb2-274"><a href="#cb2-274" aria-hidden="true" tabindex="-1"></a>})()<span class="op">;</span></span>
<span id="cb2-275"><a href="#cb2-275" aria-hidden="true" tabindex="-1"></a><span class="dt">&lt;/</span><span class="kw">script</span><span class="dt">&gt;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>